- hosts: all
  #gather_facts: false
  tasks:
   # - name: check user_id, data and time {{ inventory_hostname }}
    #  lineinfile:
     #  path: "/home/host/logs.txt"
      # line: "{{ 'By ' +  ansible_facts['user_id'] + ' in ' + ansible_date_time.time + ' ' +  ansible_date_time.date }}"
     # delegate_to: localhost

  - name: Select date
    set_fact:  
      time_info: "{{ ansible_date_time.time + '.' +  ansible_date_time.date }}"
    delegate_to: localhost

  - set_fact: papka="{{ inventory_hostname }}"
    delegate_to: "{{ item }}"
    loop: "{{ groups['mikrotiks'] }}"
    
  - set_fact: imy="{{ inventory_hostname + time_info }}"
    delegate_to: "{{ item }}"
    loop: "{{ groups['mikrotiks'] }}"
  
  - name: Export
    community.routeros.command:
      commands:
        - /export file="{{  imy }}"
    delegate_to: "{{ item }}"
    loop: "{{ groups['mikrotiks'] }}"    
    

  - name: Get export in server
    ansible.netcommon.net_get:
      protocol: sftp
      src: /{{imy}}.rsc
      dest: /runner/project/{{imy}}.rsc
    delegate_to: localhost  

  - name: Mkdir
    shell: mkdir "{{ papka }}"
    delegate_to: 192.168.1.73
  
  - name: Get copy to xaw
    ansible.builtin.copy:
      src: /runner/project/{{imy}}.rsc
      dest: /home/xaw/{{papka}}/{{imy}}.rsc
      owner: xaw
      group: xaw
      mode: u=rw,g=r,o=r
      
  
