- hosts: all
  #gather_facts: false
  tasks:
   # - name: check user_id, data and time {{ inventory_hostname }}
    #  lineinfile:
     #  path: "/home/host/logs.txt"
      # line: "{{ 'By ' +  ansible_facts['user_id'] + ' in ' + ansible_date_time.time + ' ' +  ansible_date_time.date }}"
     # delegate_to: localhost

  - name: Select date
    #gather_facts: true
    set_fact:  
      time_info: "{{ ansible_date_time.time + '.' +  ansible_date_time.date }}"
    delegate_to: localhost

  - name: Export
    set_fact:
      imy: "{{ inventory_hostname + time_info }}"
    community.routeros.command:
      commands:
        - /export file="{{ imy }}"
    

  - name: Get export in server
    ansible.netcommon.net_get:
    src: ""{{ imy }}".rsc"
    dest: /home/xaw/"{{ inventory_hostname + time_info }}".rsc
 
  - name: Show system resources
    debug:
      var: time_info
  
