- hosts: all
  #gather_facts: false
  tasks:
   # - name: check user_id, data and time {{ inventory_hostname }}
    #  lineinfile:
     #  path: "/home/host/logs.txt"
      # line: "{{ 'By ' +  ansible_facts['user_id'] + ' in ' + ansible_date_time.time + ' ' +  ansible_date_time.date }}"
     # delegate_to: localhost

  - name: Select date
    #gather_facts: true
    set_fact:  
      time_info: "{{ ansible_date_time.time + '.' +  ansible_date_time.date }}"
    delegate_to: localhost

  - name: Gather system resources
    community.routeros.command:
      commands:
        - /export file="{{ inventory_hostname +  time_info}}"
    register: system_resource_print
 
  - name: Show system resources
    debug:
      var: time_info
  
