- name: RouterOS test with network_cli connection
  gather_facts: false
- hosts: server
  tasks:
  - name: get data
    shell: "date +%Y-%m-%d%H-%M-%S"
    register: dt
  - name: Print data
    ansible.builtin.debug:
      var: dt.stdout     
  - set_fact: papka="{{ inventory_hostname }}"
  - name: Print papka
    ansible.builtin.debug:
      var: papka  

    
