- name: RouterOS test with network_cli connection
  hosts: mikrotiks
  gather_facts: true
  tasks: 

  - name: Set timezone to Asia/Tokyo
    community.general.timezone:
      name: Europe/Moscow
    delegate_to: localhost 
  - name: get time from facts
    set_fact:  
      time_info: "{{ ansible_date_time.time }}"
    delegate_to: localhost

  - name: get time from function
    set_fact:  
      time_func: "{{ now(utc=true,fmt='%Y-%m-%d %H+3:%M:%S') }}"
    delegate_to: localhost
    
  - name: time from facts
    debug:
      var: time_info     
      
  - name: time from function
    debug:
      var: time_func  
      
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts   
    delegate_to: localhost  
