#- name: RouterOS test with network_cli connection
- hosts: server 
  gather_facts: false
  tasks:
  
  - name: get data
    shell: "date +%Y-%m-%d.%H:%M:%S"
    register: dt
  - name: Touch to local
    file:
      path: "/runner/project/time"
      state: touch
    delegate_to: localhost  
  - name: Write date
    lineinfile:
      path: "/runner/project/time"
      line: "{{ dt.stdout }}"
      insertbefore: BOF
    delegate_to: localhost       
    
- hosts: mikrotiks
  gather_facts: false
  tasks:   

  - name: get data
    shell: cat /runner/project/time
    register: time_info
    delegate_to: localhost

  - set_fact: papka="{{ inventory_hostname }}"
    delegate_to: "{{ item }}"
    loop: "{{ groups['mikrotiks'] }}"
    
  - set_fact: imy="{{ inventory_hostname + time_info.stdout }}"
    delegate_to: "{{ item }}"
    loop: "{{ groups['mikrotiks'] }}"

  - name: Export
    community.routeros.command:
      commands:
        - /export file="{{  papka + ".old" }}"   

  - name: dir of backaps
    shell: mkdir /runner/project/backups
  - name: dir of hosts
    shell: mkdir /runner/project/backups/{papka}
  - name: ls
    shell: ls -p /runner/project/backups/
    register: out
  - name: debug
    debug:
      var: out

  - name: Get export in server
    ansible.netcommon.net_get:
      protocol: sftp
      src: /{{papka + ".old"}}.rsc
      dest: /runner/project/backups/{{papka}}/{{imy + ".old"}}.rsc  
      ignore_errors: true  
      
- hosts: server
  gather_facts: false
  tasks:

  - name: copy backups to xaw user dir
    copy:
      src: /runner/project/backups
      dest: /home/xaw/
      owner: xaw
      group: xaw        
      mode: 0644    

    
