- name: RouterOS test with network_cli connection
  hosts: mikrotiks
  gather_facts: false
  tasks:

  - name: ls
    shell: ls /runner -p
    register: outtext
    delegate_to: localhost

  - name: gfgf
    debug:
      var: outtext
