#- name: RouterOS test with network_cli connection
- hosts: mikrotiks
  gather_facts: false
  tasks:   

  - set_fact: tm="{{ now(utc=true,fmt='%Y-%m-%d %H:%M:%S') }}"
    delegate_to: localhost
  - name: Print time
    ansible.builtin.debug:
      var: tm[11]+3 
    delegate_to: localhost  

    
