- name: RouterOS test with network_cli connection
  hosts: all
  gather_facts: false
  tasks:

  - name: ls
    shell: ls
    register: outtext
    delegate_to: localhost

  - name: gfgf
    debug:
      var: outtext
