#- name: RouterOS test with network_cli connection
- hosts: all  
  gather_facts: false
  tasks:

  - name: Set timezone to Asia/Tokyo
    community.general.timezone:
    name: Europe/Moscow
    delegate_to: localhost
  - name: get data
    shell: "date +%Y-%m-%d.%H:%M:%S"
    register: dt
  - name: Print data
    ansible.builtin.debug:
      var: dt.stdout     
  - set_fact: papka="{{ inventory_hostname }}"
  - name: Print papka
    ansible.builtin.debug:
      var: papka  

    
