- hosts: mikrotiks
  gather_facts: false
  tasks: 

  - name: Получение версии роутеров
    ansible.builtin.include_tasks: version.yml
    
  - name: Дебаг
    debug: 
      msg: version is 7
    when: "{{ first_num_of_ver }}" = "7"  
