---
- hosts: 192.168.1.73 
  gather_facts: false
  tasks:
  
  - name: get data
    shell: "date +%Y-%m-%d.%H:%M:%S"
    register: dt
  - name: Print data
    ansible.builtin.debug:
      var: dt.stdout     
  - set_fact: tm="{{ dt.stdout }}"
    delegate_to: localhost

- hosts: mikrotiks
  gather_facts: false
  tasks:
  - name: Apply tags to tasks within included file when using free-form
    ansible.builtin.include_tasks:
      file: backup.yml
