---
- hosts: server
  tasks:
  - name: Сравнение файлов
    shell: diff old.rsc new.rsc
    register: out
    failed_when: “wp.rc not in [ 0, 1 ]”
  - name: Вывод команды
    debug:
      var: out.stdout_lines
  - name: Вывод длины массива
    debug:
      var: "{{ out.stdout_lines|length }}"
