---
- hosts: server
  tasks:
  - name: Сравнение файлов
    shell: ls -p
    register: out
  - name: Вывод команды
    debug:
      var: out.stdout_lines
  - name: Вывод длины массива
    debug:
      var: "{{ out.stdout_lines|length }}"
