- hosts: mikrotiks
  gather_facts: false
  tasks:

  #- name: Export
   # community.routeros.command:
    #  commands:
     #   - /ip firewall/nat/print where comment=ub
    #register: firewall

  - name: cat
    shell: cat /runner/project/config.rsc
    register: firewall
  - set_fact:
      numbers_mas: "{{ firewall.stdout | regex_search('\\d+') }}"
    
  - set_fact:
      numbers: "{{ numbers_mas | join(',') }}"

 # - name: Remove
  #  community.routeros.command:
   #   commands:
    #    - /ip firewall/nat/ remove numbers="{{ numbers }}"
  - name: Вывод
    debug:
      var: numbers
    
