- hosts: all
  gather_facts: false
  tasks:

  - name: Export
    community.routeros.command:
      commands:
        - /ip firewall/filter/print proplist=comment
    register: firewall
    
  - set_fact:
      numbers_mas: "{{ firewall.stdout | regex_findall('\\d+') }}"
    delegate_to: "{{ item }}"
    loop: "{{ groups['mikrotiks'] }}"
    
  - set_fact:
      numbers: "{{ numbers_mas | join(',') }}"
    delegate_to: "{{ item }}"
    loop: "{{ groups['mikrotiks'] }}"  

  - name: Out
    debug:
      var: numbers

  - name: Out
    debug:
      var: firewall.stdout

  - name: Remove
    community.routeros.command:
      commands:
        - /ip firewall/filter/remove numbers=1
    register: out
    
  - name: Out
    debug:
      var: out.stdout  
  
    
