- hosts: mikrotiks
  gather_facts: false
  tasks:

  - name: Export
    community.routeros.command:
      commands:
        - /ip firewall/nat/print where comment=ub
    register: firewall
    
  - set_fact:
      numbers_mas: "{{ firewall.stdout | regex_findall('\d+') }}"
    
  - set_fact:
      numbers: "{{ numbers_mas | join(',') }}"

 # - name: Remove
  #  community.routeros.command:
   #   commands:
    #    - /ip firewall/nat/ remove numbers="{{ numbers }}"
   - name: Вывод
     debug:
       var: numbers
    
