- hosts: all
  gather_facts: false
  tasks:

  - name: Cat
    shell: cat /runner/project/config.rsc
    register: firewall
  
  - set_fact:
      numbers: "{{ firewall.stdout | regex_search('\\d+') }}"
    delegate_to: localhost

  - name: Out
    debug:
      var: numbers

  - name: Out
    debug:
      var: firewall.stdout
  
    
