- hosts: all
  gather_facts: false
  tasks:

  - name: Cat
    shell: cat /runner/project/config.rsc
    register: firewall
  
  - set_fact:
      numbers_mas: "{{ firewall.stdout | regex_findall('\\d+') }}"
    delegate_to: localhost
    
  - set_fact:
      numbers: "{{ numbers_mas | join(',') }}"
    delegate_to: localhost  

  - name: Out
    debug:
      var: numbers

  - name: Out
    debug:
      var: firewall.stdout
  
    
