---
- hosts: localhost
  gather_facts: false
  tasks:

  - name: ls
    shell: ls /runner/papka
    register: out
    #failed_when: "out.rc not in [ 0, 127 ]"
  - name: print
    debug:
      var: out
