- hosts: all
  gather_facts: false
  tasks:

  - name: cope
    copy:
      src: /runner/project
      dest: /home/xaw/
      owner: xaw
      group: xaw        
      mode: 0644
    delegate_to: localhost  
