---
- hosts: mikrotiks
  tasks:

  - set_fact: papka="{{ inventory_hostname }}"
    
  - set_fact: imy="{{ inventory_hostname + ".test" }}"

  - name: Export
    community.routeros.command:
      commands:
        - /export file="{{  papka + ".old" }}"   

  - name: dir of backaps
    shell: mkdir /runner/project/backups
  - name: dir of hosts
    shell: mkdir /runner/project/backups/{{papka}}

  - name: Get export in server
    ansible.netcommon.net_get:
      protocol: sftp
      src: /{{papka + ".old"}}.rsc
      dest: /runner/project/backups/{{papka}}/{{imy + ".old"}}.rsc  
      ignore_errors: true

  - name: Запись конфигурации в строку
    shell: cat /runner/project/backups/{{papka}}/{{imy + ".old"}}.rsc
    register: cfgold

  - name: debug
    debug: 
      var: cfgold.stdout_lines[1:]

  - name: Export in variable
    community.routeros.command:
      commands:
        - /export
    register: cfgnew     

  - name: debug
    debug: 
      var: cfgnew.stdout_lines[1:]  

  - set_fact: difer="True"
    when: cfgold.stdout_lines[1:] != cfgnew.stdout_lines[1:]

  - name: Export to file
    community.routeros.command:
      commands:
        - /export file="{{  papka + ".new" }}"  
    when: difer == "True"    

  - name: Get export in server
    ansible.netcommon.net_get:
      protocol: sftp
      src: /{{papka + ".new"}}.rsc
      dest: /runner/project/backups/{{papka}}/{{imy + ".new"}}.rsc  
      ignore_errors: true
    when: difer == "True"
      
      
  
